# Generated by Django 2.0.1 on 2018-02-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('Masculino', 'Hombre'), ('Femenino', 'Mujer')], max_length=140)),
                ('imagen', models.ImageField(upload_to='images/peliculas/actores')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('fecha_nacimiento', models.DateField()),
                ('imagen', models.ImageField(upload_to='images/peliculas/directores')),
                ('sexo', models.CharField(choices=[('Masculino', 'Hombre'), ('Femenino', 'Mujer')], max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('duracion', models.DurationField()),
                ('sinopsis', models.TextField()),
                ('portada', models.ImageField(upload_to='images/peliculas')),
                ('estreno', models.BooleanField(default=False)),
                ('actores', models.ManyToManyField(related_name='peliculas', to='peliculas.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='peliculas.Director')),
            ],
        ),
    ]
