# Generated by Django 2.0.1 on 2018-01-24 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadoramodel',
            name='procesador',
            field=models.CharField(choices=[('Intel i3', 'Intel - i3'), ('Intel i5', 'Intel - i5'), ('Intel i7', 'Intel - i7'), ('AMD A6', 'AMD - A6'), ('AMD A8', 'AMD - A8'), ('AMD A10', 'AMD - A10')], default=django.utils.timezone.now, max_length=140),
            preserve_default=False,
        ),
    ]
